### ISSUE TITLE
Release as open source?

### ISSUE THREAD

**Issue by dpriskorn** [carlosfranzreb/thesis_openalex#1]

**Comment by carlosfranzreb** [comment]
Hello! This is the code for my Master's thesis, which I'm giving in tomorrow. Afterwards, I will clean up the code and add a license. Feel free to use anything you want.

**Comment by dpriskorn** [comment]
Would you be willing to share the thesis as well?

**Comment by carlosfranzreb** [comment]
I don't know if I'm allowed to before it has been graded. At some point it should be possible. I'll ask my supervisor!

**Comment by carlosfranzreb** [comment]
Hello @dpriskorn. I have cleaned up the code and added a license. You can find the new repo [here](https://github.com/carlosfranzreb/openalex4ml). It does not include all the details of my own implementation, which are not useful to others. If you have any suggestions on how to improve it, please post an issue there. Thank you for your interest!
